Initialize the actual GPIO state to on/high
canonical/matter-pi-gpio-commander pull request #15
Opened 2023-04-25 08:19 UTC by farshidtz

Related to #14, this is a quick fix to force a synchronized state. 

Turning on a device upon startup is the state of practice in smart lighting. The negative side effect for this application is that the GPIO will be set HIGH also during app updates.

2023-04-26 08:15 UTC, MonicaisHer commented on app/src/LightingManager.cpp
> +    // initialize the stored and actual to on
```suggestion
    // initialize both the stored and actual value to 'on'
```

2023-04-26 10:39 UTC, MonicaisHer approved these changes
Thank you, looks good!

2023-04-27 13:34 UTC, MonicaisHer requested changes
I installed the snap built from this PR on a Raspberry Pi 3 running Ubuntu Core OS using the command:
```
sudo snap install matter-pi-gpio-commander --channel=edge/pr-15
```
After installation, the LED was initially off. Upon issuing the 1st toggle command, the LED remained off, but the log indicated that it had toggled from 0 to 1. Similarly, the 2nd toggle command also resulted in the LED remaining off, but the log indicated that it had toggled from 1 to 0. Finally, upon issuing the 3rd toggle command, the LED turned on, and the log indicated that it had toggled from 0 to 1 as well.

It appears the results obtained with this PR were identical to those obtained with the existing code. There could be an issue that `digitalWrite(gpio, HIGH)` call not turning the LED on initially.


Logs from the above three toggle commands for debugging: https://pastebin.ubuntu.com/p/s7Y3xJnwVQ/

2023-04-27 18:23 UTC, farshidtz commented
Thanks a lot for testing. 

> After installation, the LED was initially off. Upon issuing the 1st toggle command, the LED remained off, but the log indicated that it had toggled from 0 to 1.

This is strange because it indicates that the SDK isn't capturing the set ON state correctly. 

> It appears the results obtained with this PR were identical to those obtained with the existing code. There could be an issue that `digitalWrite(gpio, HIGH)` call not turning the LED on initially.

The branch may have contained a build from main. Could you please give it another try? It should be revision 14. 
After config (gpio, connections), the service startup should be followed by turning the gpio to on/high.

A subsequent "off" command should turn it off. But given the above concern regarding the SDK, the "off" will probably lead to a message saying the device is set to off. See https://github.com/canonical/matter-pi-gpio-commander/issues/14#issuecomment-1517659754

2023-04-28 07:53 UTC, MonicaisHer commented
I got the same result using the edge/pr-15 channel,  LED only turns on until the third toggle command is sent. Please the steps and logs:
```
$ sudo snap install matter-pi-gpio-commander --channel=edge/pr-15
$ snap info matter-pi-gpio-commander
installed:          0.3.0            (14) 12MB -
$ sudo snap set matter-pi-gpio-commander gpio=26
$ sudo snap connect matter-pi-gpio-commander:avahi-control avahi:avahi-control
$ sudo snap connect matter-pi-gpio-commander:gpio-memory-control
$ sudo snap start matter-pi-gpio-commander
```
```
$ sudo chip-tool pairing ethernet 110 20202021 3840 192.168.178.71 5540
$ sudo chip-tool onoff toggle 110 1
```

matter-pi-gpio-commander logs: https://pastebin.ubuntu.com/p/HRJM6kjmzy/

2023-04-28 14:09 UTC, MonicaisHer approved these changes
It works as expected using the snap built from this PR.

2023-04-28 18:55 UTC, merged

2023-04-28 18:56 UTC, farshidtz commented
Thank you for testing @MonicaisHer.