Update Matter SDK to 1.2.0.1
canonical/matter-pi-gpio-commander pull request #33
Opened 2023-11-08 10:55 UTC by MonicaisHer

This PR updates Matter SDK to 1.2.0.1 and rebases local lighting application code to upstream v1.2.0.1

2023-11-08 14:17 UTC, farshidtz commented
The upgrade involves several Thread-related changes. These were added during the upgrade to the development version in https://github.com/canonical/matter-pi-gpio-commander/pull/28

Diff: https://github.com/canonical/matter-pi-gpio-commander/compare/main...thread
The thread branch could be merged into the current one.

2023-11-09 09:14 UTC, MonicaisHer commented
The commander can't be discovered by chip-tool. The openthread border router agent, running on the same machine as matter-pi-gpio-commander, shows a D-Bus error:
```
2023-11-09T09:05:53Z openthread-border-router.otbr-agent[1959]: otbr-agent[1959]: 00:00:00.087 [I] Platform------: [netif] Host netif is down
2023-11-09T09:05:53Z otbr-agent[1959]: [WARN]-BA------: Result of publish meshcop service OpenThread BorderRouter #9914._meshcop._udp.local: Invalid state
2023-11-09T09:05:53Z otbr-agent[1959]: 00:00:00.087 [I] Platform------: [netif] Host netif is down
2023-11-09T09:08:12Z openthread-border-router.otbr-agent[1959]: otbr-agent[1959]: [INFO]-DBUS----: Handling method org.freedesktop.DBus.Properties.GetAll
2023-11-09T09:08:12Z openthread-border-router.otbr-agent[1959]: otbr-agent[1959]: [ERR ]-UTILS---: Replied to org.freedesktop.DBus.Properties.GetAll with result io.openthread.Error.Detached
2023-11-09T09:08:12Z otbr-agent[1959]: [INFO]-DBUS----: Handling method org.freedesktop.DBus.Properties.GetAll
2023-11-09T09:08:12Z otbr-agent[1959]: [ERR ]-UTILS---: Replied to org.freedesktop.DBus.Properties.GetAll with result io.openthread.Error.Detached
```
full logs: https://pastebin.ubuntu.com/p/RSX6VZfHPp/

2023-11-10 07:55 UTC, MonicaisHer commented
Using the latest tested version on matter-pi-gpio-commander, the dbus error also appears on otbr side. The error might be related to OTBR itself, but not commander:
```
sudo snap install matter-pi-gpio-commander --channel=latest/edge/thread
```

2023-11-17 10:18 UTC, MonicaisHer commented
Issue opened: https://github.com/openthread/openthread/issues/9605

2023-11-23 21:28 UTC, farshidtz commented
I don't get any error on OTBR but commissioning via Chip Tool fails with the following error: `Error on commissioning step 'ThreadNetworkEnable'`

More logs:
```
[1700774087.216912][18406:18429] CHIP:CTL: Performing next commissioning step 'ThreadNetworkSetup'
[1700774087.216931][18406:18429] CHIP:DMG: ICR moving to [AddingComm]
[1700774087.216939][18406:18429] CHIP:DMG: ICR moving to [AddedComma]
[1700774087.216964][18406:18429] CHIP:EM: <<< [E:37475i S:5869 M:211761504] (S) Msg TX to 0:FFFFFFFB00000000 [0000] [BLE] --- Type 0001:08 (IM:InvokeCommandRequest)
[1700774087.217118][18406:18429] CHIP:DMG: ICR moving to [CommandSen]
[1700774087.217140][18406:18429] CHIP:DMG: ICR moving to [AwaitingDe]
[1700774087.308030][18406:18429] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1700774087.308347][18406:18428] CHIP:DL: Indication received, conn = 0x7f73d802be80
[1700774087.308378][18406:18429] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1700774087.308433][18406:18429] CHIP:EM: >>> [E:37475i S:5869 M:217608970] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
[1700774087.308442][18406:18429] CHIP:EM: Found matching exchange: 37475i, Delegate: 0x7f73d000a1e8
[1700774087.308459][18406:18429] CHIP:DMG: ICR moving to [ResponseRe]
[1700774087.308477][18406:18429] CHIP:DMG: InvokeResponseMessage =
[1700774087.308481][18406:18429] CHIP:DMG: {
[1700774087.308486][18406:18429] CHIP:DMG: 	suppressResponse = false, 
[1700774087.308490][18406:18429] CHIP:DMG: 	InvokeResponseIBs =
[1700774087.308498][18406:18429] CHIP:DMG: 	[
[1700774087.308502][18406:18429] CHIP:DMG: 		InvokeResponseIB =
[1700774087.308510][18406:18429] CHIP:DMG: 		{
[1700774087.308515][18406:18429] CHIP:DMG: 			CommandDataIB =
[1700774087.308521][18406:18429] CHIP:DMG: 			{
[1700774087.308526][18406:18429] CHIP:DMG: 				CommandPathIB =
[1700774087.308532][18406:18429] CHIP:DMG: 				{
[1700774087.308538][18406:18429] CHIP:DMG: 					EndpointId = 0x0,
[1700774087.308546][18406:18429] CHIP:DMG: 					ClusterId = 0x31,
[1700774087.308552][18406:18429] CHIP:DMG: 					CommandId = 0x5,
[1700774087.308560][18406:18429] CHIP:DMG: 				},
[1700774087.308571][18406:18429] CHIP:DMG: 				
[1700774087.308577][18406:18429] CHIP:DMG: 				CommandFields = 
[1700774087.308584][18406:18429] CHIP:DMG: 				{
[1700774087.308591][18406:18429] CHIP:DMG: 					0x0 = 0, 
[1700774087.308597][18406:18429] CHIP:DMG: 					0x2 = 0, 
[1700774087.308603][18406:18429] CHIP:DMG: 				},
[1700774087.308609][18406:18429] CHIP:DMG: 			},
[1700774087.308616][18406:18429] CHIP:DMG: 			
[1700774087.308623][18406:18429] CHIP:DMG: 		},
[1700774087.308630][18406:18429] CHIP:DMG: 		
[1700774087.308635][18406:18429] CHIP:DMG: 	],
[1700774087.308643][18406:18429] CHIP:DMG: 	
[1700774087.308648][18406:18429] CHIP:DMG: 	InteractionModelRevision = 11
[1700774087.308652][18406:18429] CHIP:DMG: },
[1700774087.308672][18406:18429] CHIP:DMG: Received Command Response Data, Endpoint=0 Cluster=0x0000_0031 Command=0x0000_0005
[1700774087.308685][18406:18429] CHIP:CTL: Received NetworkConfig response, networkingStatus=0
[1700774087.308697][18406:18429] CHIP:CTL: Successfully finished commissioning step 'ThreadNetworkSetup'
[1700774087.308705][18406:18429] CHIP:CTL: Commissioning stage next step: 'ThreadNetworkSetup' -> 'FailsafeBeforeThreadEnable'
[1700774087.308712][18406:18429] CHIP:CTL: Performing next commissioning step 'FailsafeBeforeThreadEnable'
[1700774087.308722][18406:18429] CHIP:CTL: Arming failsafe (66 seconds)
[1700774087.308737][18406:18429] CHIP:DMG: ICR moving to [AddingComm]
[1700774087.308744][18406:18429] CHIP:DMG: ICR moving to [AddedComma]
[1700774087.308764][18406:18429] CHIP:EM: <<< [E:37476i S:5869 M:211761505] (S) Msg TX to 0:FFFFFFFB00000000 [0000] [BLE] --- Type 0001:08 (IM:InvokeCommandRequest)
[1700774087.308890][18406:18429] CHIP:DMG: ICR moving to [CommandSen]
[1700774087.308913][18406:18429] CHIP:DMG: ICR moving to [AwaitingDe]
[1700774087.396026][18406:18429] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1700774087.396339][18406:18428] CHIP:DL: Indication received, conn = 0x7f73d802be80
[1700774087.396375][18406:18429] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1700774087.396452][18406:18429] CHIP:EM: >>> [E:37476i S:5869 M:217608971] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
[1700774087.396461][18406:18429] CHIP:EM: Found matching exchange: 37476i, Delegate: 0x7f73d003e8f8
[1700774087.396474][18406:18429] CHIP:DMG: ICR moving to [ResponseRe]
[1700774087.396492][18406:18429] CHIP:DMG: InvokeResponseMessage =
[1700774087.396497][18406:18429] CHIP:DMG: {
[1700774087.396501][18406:18429] CHIP:DMG: 	suppressResponse = false, 
[1700774087.396506][18406:18429] CHIP:DMG: 	InvokeResponseIBs =
[1700774087.396513][18406:18429] CHIP:DMG: 	[
[1700774087.396517][18406:18429] CHIP:DMG: 		InvokeResponseIB =
[1700774087.396529][18406:18429] CHIP:DMG: 		{
[1700774087.396535][18406:18429] CHIP:DMG: 			CommandDataIB =
[1700774087.396544][18406:18429] CHIP:DMG: 			{
[1700774087.396551][18406:18429] CHIP:DMG: 				CommandPathIB =
[1700774087.396559][18406:18429] CHIP:DMG: 				{
[1700774087.396565][18406:18429] CHIP:DMG: 					EndpointId = 0x0,
[1700774087.396574][18406:18429] CHIP:DMG: 					ClusterId = 0x30,
[1700774087.396579][18406:18429] CHIP:DMG: 					CommandId = 0x1,
[1700774087.396585][18406:18429] CHIP:DMG: 				},
[1700774087.396592][18406:18429] CHIP:DMG: 				
[1700774087.396600][18406:18429] CHIP:DMG: 				CommandFields = 
[1700774087.396605][18406:18429] CHIP:DMG: 				{
[1700774087.396612][18406:18429] CHIP:DMG: 					0x0 = 0, 
[1700774087.396620][18406:18429] CHIP:DMG: 					0x1 = "" (0 chars), 
[1700774087.396626][18406:18429] CHIP:DMG: 				},
[1700774087.396632][18406:18429] CHIP:DMG: 			},
[1700774087.396639][18406:18429] CHIP:DMG: 			
[1700774087.396644][18406:18429] CHIP:DMG: 		},
[1700774087.396650][18406:18429] CHIP:DMG: 		
[1700774087.396655][18406:18429] CHIP:DMG: 	],
[1700774087.396663][18406:18429] CHIP:DMG: 	
[1700774087.396668][18406:18429] CHIP:DMG: 	InteractionModelRevision = 11
[1700774087.396672][18406:18429] CHIP:DMG: },
[1700774087.396692][18406:18429] CHIP:DMG: Received Command Response Data, Endpoint=0 Cluster=0x0000_0030 Command=0x0000_0001
[1700774087.396704][18406:18429] CHIP:CTL: Received ArmFailSafe response errorCode=0
[1700774087.396713][18406:18429] CHIP:CTL: Successfully finished commissioning step 'FailsafeBeforeThreadEnable'
[1700774087.396719][18406:18429] CHIP:CTL: Commissioning stage next step: 'FailsafeBeforeThreadEnable' -> 'ThreadNetworkEnable'
[1700774087.396724][18406:18429] CHIP:CTL: Performing next commissioning step 'ThreadNetworkEnable'
[1700774087.396742][18406:18429] CHIP:DMG: ICR moving to [AddingComm]
[1700774087.396749][18406:18429] CHIP:DMG: ICR moving to [AddedComma]
[1700774087.396769][18406:18429] CHIP:EM: <<< [E:37477i S:5869 M:211761506] (S) Msg TX to 0:FFFFFFFB00000000 [0000] [BLE] --- Type 0001:08 (IM:InvokeCommandRequest)
[1700774087.396878][18406:18429] CHIP:DMG: ICR moving to [CommandSen]
[1700774087.396901][18406:18429] CHIP:DMG: ICR moving to [AwaitingDe]
[1700774087.487864][18406:18429] CHIP:DL: HandlePlatformSpecificBLEEvent 16387
[1700774087.488266][18406:18428] CHIP:DL: Indication received, conn = 0x7f73d802be80
[1700774087.488318][18406:18429] CHIP:DL: HandlePlatformSpecificBLEEvent 16389
[1700774087.488433][18406:18429] CHIP:EM: >>> [E:37477i S:5869 M:217608972] (S) Msg RX from 0:FFFFFFFB00000000 [0000] --- Type 0001:09 (IM:InvokeCommandResponse)
[1700774087.488443][18406:18429] CHIP:EM: Found matching exchange: 37477i, Delegate: 0x7f73d000a1e8
[1700774087.488460][18406:18429] CHIP:DMG: ICR moving to [ResponseRe]
[1700774087.488480][18406:18429] CHIP:DMG: InvokeResponseMessage =
[1700774087.488485][18406:18429] CHIP:DMG: {
[1700774087.488490][18406:18429] CHIP:DMG: 	suppressResponse = false, 
[1700774087.488495][18406:18429] CHIP:DMG: 	InvokeResponseIBs =
[1700774087.488504][18406:18429]  [...]

2023-11-24 09:36 UTC, MonicaisHer commented
@farshidtz The error 'Error on commissioning step 'ThreadNetworkEnable'' might be caused by the border router side not being ready. Could you confirm that the Thread network is formed and active on the border router side by using the 'openthread-border-router.ot-ctl state' command?

Reference: https://github.com/project-chip/connectedhomeip/issues/28723#issuecomment-1682995765

2023-11-24 16:45 UTC, farshidtz commented
The `Error on commissioning step 'ThreadNetworkEnable'` error was caused by a misconfiguration on my setup on Raspberry Pi. I was using an older OTBR agent which had a different DBus snap interface name.

2023-11-24 17:13 UTC, farshidtz commented
I can commission and toggle with Home Assistant Libs' Python Matter Server, but the GPIO state does not change. 

The following error does appear in OTBR logs (On the Pi side), but it isn't fatal since I can still commission and control:
```
2023-11-24T16:54:59Z otbr-agent[19730]: [INFO]-DBUS----: Handling method org.freedesktop.DBus.Properties.GetAll
2023-11-24T16:54:59Z otbr-agent[19730]: [ERR ]-UTILS---: Replied to org.freedesktop.DBus.Properties.GetAll with result io.openthread.Error.Detached
```

HA requests/responses:

Set Thread dataset:
```json
{
  "message_id": "1",
  "command": "set_thread_dataset",
  "args": {
    "dataset": "0e080000000000010000000300001035060004001fffe00208a4beadc4c3b0402f0708fd6c14d1b8295f080510e0e84c90fe5b95c80b2a72f146bb40fb030f4f70656e5468726561642d623534320102b54204104b7b78b8b761fdbe27594e9fbd133eb40c0402a0f7f8"
  }
}
{
  "message_id": "1",
  "result": null
}
```
Commission:
```json
{
  "message_id": "2",
  "command": "commission_with_code",
  "args": {
    "code": "MT:-24J042C00KA0648G00"
  }
}
{
  "message_id": "2",
  "result": {
    "node_id": 2, <used in the next request>
    "date_commissioned": "2023-11-24T16:57:02.935773",
    "last_interview": "2023-11-24T16:57:02.935775",
    "interview_version": 4,
    "available": true,
    ...
}
```



Toggle:
```json
{
  "message_id": "3",
  "command": "device_command",
  "args": {
    "endpoint_id": 1,
    "node_id": 2,
    "payload": {},
    "cluster_id": 6,
    "command_name": "Toggle"
  }
}
{
  "message_id": "3",
  "result": null
}
```

2023-11-24 18:10 UTC, farshidtz requested changes
The GPIO control is broken (tested over both WiFi and Thread). It appears that [`LightingManager::Set(bool aOn)`](https://github.com/MonicaisHer/matter-pi-gpio-commander/blob/88512d2b7ea0d07012ed5273a413a10024898416/app/src/LightingManager.cpp#L122-L134) which toggles that the GPIO state is no longer being called.

2023-11-27 14:49 UTC, MonicaisHer commented
> The GPIO control is broken (tested over both WiFi and Thread). It appears that [`LightingManager::Set(bool aOn)`](https://github.com/MonicaisHer/matter-pi-gpio-commander/blob/88512d2b7ea0d07012ed5273a413a10024898416/app/src/LightingManager.cpp#L122-L134) which toggles that the GPIO state is no longer being called.

Thanks for testing. The build script was using an upstream source to build the lighting manager, resulting in the GPIO control not working. The build script has since been modified to use the local source for the lighting manager build. The snap can now be commissioned and toggled via chip-tool over WiFi.

The snap could be installed by running:
```
sudo snap install matter-pi-gpio-commander --channel=latest/edge/pr33
```

2023-12-01 13:54 UTC, farshidtz reviewed
It works now. Thanks.
Tested over WiFi with Chip Tool 1.2.0.1.

2023-12-01 13:54 UTC, farshidtz approved these changes

2023-12-01 13:56 UTC, merged