Add workflow for weekly build and publish of snap
canonical/matter-pi-gpio-commander pull request #71
Opened 2024-06-13 12:18 UTC by jpm-canonical

## Summary
The github workflow builds, tests and publishes the snap. Build is done in Qemu on amd64, building only for arm64. Test is done on native arm64. Publish is done on amd64. The workflow is triggered weekly to pull in latest matter sdk.

## Testing Steps

Check github action output of this PR, or after it is merged the output of the weekly triggered action.

2024-06-13 14:54 UTC, farshidtz commented
Supersedes #66

2024-06-13 15:28 UTC, jpm-canonical commented
Test is failing with this error:
```
[SETUP]
[exec] ./gpio-mock.sh
[exec] rm -rf squashfs-root
[exec] unsquashfs ..//home/runner/work/matter-pi-gpio-commander/matter-pi-gpio-commander/matter-pi-gpio-commander_2.0.0_arm64.snap
stderr: Could not open ..//home/runner/work/matter-pi-gpio-commander/matter-pi-gpio-commander/matter-pi-gpio-commander_2.0.0_arm64.snap, because No such file or directory
err: exit status 1
```

2024-06-14 21:50 UTC, locnnil requested changes

2024-06-14 21:50 UTC, locnnil commented on .github/workflows/build-and-test-snap.yml
> +          LOCAL_SERVICE_SNAP: ../${{ needs.build-arm64.outputs.snap }}
You're referring it using the environment variable which gives you an absolute path, removing `../` should fix it: 

```suggestion
          LOCAL_SERVICE_SNAP: ${{ needs.build-arm64.outputs.snap }}
```

2024-06-15 14:48 UTC, locnnil reviewed
Now [the problem](https://github.com/canonical/matter-pi-gpio-commander/actions/runs/9522778831/job/26254542770#step:5:40) is actually related with the gpio mockup module.

2024-08-13 06:49 UTC, closed without merging